// Copyright 2026 Antifraud Services Inc. under the Apache License, Version 2.0.

/**
 * Re-export MedicationStatement claim helpers from common-utils so SDK CORE
 * consumers can discover the canonical flat-claim APIs from the same package
 * that handles draft/outbox orchestration.
 */
export {
  addMedicationCategoryList,
  addMedicationClaimList,
  addMedicationCodeList,
  addMedicationContainedDocumentIdentifierList,
  addMedicationPartOfList,
  addMedicationSourceList,
  addMedicationSubjectList,
  getMedicationCategoryList,
  getMedicationClaimList,
  getMedicationCodeList,
  getMedicationContainedDocumentIdentifierList,
  getMedicationDosageAsNeeded,
  getMedicationDoseQuantityUnit,
  getMedicationDoseQuantityValue,
  getMedicationEffective,
  getMedicationIdentifier,
  getMedicationPartOfList,
  getMedicationSourceList,
  getMedicationStatus,
  getMedicationSubject,
  getMedicationSubjectList,
  getMedicationText,
  getMedicationTimingFrequency,
  getMedicationTimingPeriod,
  getMedicationTimingPeriodUnit,
  removeMedicationCategoryList,
  removeMedicationClaimList,
  removeMedicationCodeList,
  removeMedicationContainedDocumentIdentifierList,
  removeMedicationPartOfList,
  removeMedicationSourceList,
  removeMedicationSubjectList,
  setMedicationCategoryList,
  setMedicationClaimList,
  setMedicationCodeList,
  setMedicationContainedDocumentIdentifierList,
  setMedicationDosageAsNeeded,
  setMedicationDoseQuantityUnit,
  setMedicationDoseQuantityValue,
  setMedicationEffective,
  setMedicationIdentifier,
  setMedicationPartOfList,
  setMedicationSourceList,
  setMedicationStatus,
  setMedicationSubject,
  setMedicationSubjectList,
  setMedicationText,
  setMedicationTimingFrequency,
  setMedicationTimingPeriod,
  setMedicationTimingPeriodUnit,
  type MedicationInteroperableClaims,
} from 'gdc-common-utils-ts/utils/medication-claim-helpers';
